locals {
  region           = "us-west-2"
  aws_region       = "us-west-2"
  company_code     = "sdge"
  application_code = "iac"
  environment_code = "sbx"
  region_code      = "wus2"
  namespace        = "iac-sbx-aws.sempra.com"
  owner            = "IAC team"
}

provider "aws" {
  region = local.region
}

module "athena_example" {
  source  = "app.terraform.io/SempraUtilities/seu-athena/aws"
  version = "x.x.x"

  company_code     = local.company_code
  application_code = local.application_code
  environment_code = local.environment_code
  region_code      = local.region_code
  application_use  = "athena-test"
  tags = {
    name                = "test"
    portfolio           = "IaC"
    unit                = "12345"
    tag-version         = "Holds the version of the tagging format."
    billing-guid        = "Internal order - from SAP"
    support-group       = "Distribution list in email format"
    environment         = "Environment deployed"
    cmdb-ci-id          = "CI ID as generated by ServiceNow CMDB"
    data-classification = "Data privacy classification"
  }

  create_athena_named_query = true
  named_query_name          = "iac_test_query"
  named_query_description   = "iac test named query"
  named_query_workgroup     = "my-workgroup"
  named_query_database      = "my-database-name"
  named_query_query         = "SELECT * FROM my-table;"

  create_workgroup       = false
  create_athena_database = false
}
