locals {
  region           = "us-west-2"
  aws_region       = "us-west-2"
  company_code     = "sdge"
  application_code = "iac"
  environment_code = "sbx"
  region_code      = "wus2"
  namespace        = "iac-sbx-aws.sempra.com"
  owner            = "IAC team"
}

provider "aws" {
  region = local.region
}

module "athena_example" {
  source  = "app.terraform.io/SempraUtilities/seu-athena/aws"
  version = "x.x.x"

  company_code     = local.company_code
  application_code = local.application_code
  environment_code = local.environment_code
  region_code      = local.region_code
  application_use  = "athena-test"
  tags = {
    name                = "test"
    portfolio           = "IaC"
    unit                = "12345"
    tag-version         = "Holds the version of the tagging format."
    billing-guid        = "Internal order - from SAP"
    support-group       = "Distribution list in email format"
    environment         = "Environment deployed"
    cmdb-ci-id          = "CI ID as generated by ServiceNow CMDB"
    data-classification = "Data privacy classification"
  }

  create_workgroup                   = true
  workgroup_force_destroy            = true
  workgroup_description              = "Example IaC Athena Workgroup"
  enforce_workgroup_configuration    = true
  publish_cloudwatch_metrics_enabled = true
  output_location                    = "s3://my-s3-bucket/output/"
  workgroup_encryption_option        = "SSE_KMS"
  workgroup_kms_key_arn              = "my-athena-kms-key-arn"

  create_athena_database    = false
  create_athena_named_query = false
}
